-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 14:33:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TousEnVacancesBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TousEnVacancesBD` ;

-- -----------------------------------------------------
-- Schema TousEnVacancesBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TousEnVacancesBD` DEFAULT CHARACTER SET utf8 ;
USE `TousEnVacancesBD` ;

-- -----------------------------------------------------
-- Table `TousEnVacancesBD`.`EMPLOYE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TousEnVacancesBD`.`EMPLOYE` ;

CREATE TABLE IF NOT EXISTS `TousEnVacancesBD`.`EMPLOYE` (
  `ID_EMPLOYE` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NOT NULL,
  `PRENOM` VARCHAR(45) NOT NULL,
  `GRADE` VARCHAR(45) NOT NULL DEFAULT 'employe',
  `ADRESSE_MAIL` VARCHAR(45) NULL DEFAULT NULL,
  `NUMERO_TELEPHONE` VARCHAR(15) NULL DEFAULT NULL,
  `URL_PHOTO` VARCHAR(45) NULL DEFAULT NULL,
  `ID_MANAGER` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_EMPLOYE`),
  CONSTRAINT `fk_EMPLOYE_MANAGER`
    FOREIGN KEY (`ID_MANAGER`)
    REFERENCES `TousEnVacancesBD`.`EMPLOYE` (`ID_EMPLOYE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_EMPLOYE_UNIQUE` ON `TousEnVacancesBD`.`EMPLOYE` (`ID_EMPLOYE` ASC) ;

CREATE INDEX `fk_EMPLOYE_MANAGER_idx` ON `TousEnVacancesBD`.`EMPLOYE` (`ID_MANAGER` ASC) ;

CREATE INDEX `fk_EMPLOYE_MANAGER` ON `TousEnVacancesBD`.`EMPLOYE` (`ID_MANAGER` ASC) ;


-- -----------------------------------------------------
-- Table `TousEnVacancesBD`.`COMPTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TousEnVacancesBD`.`COMPTE` ;

CREATE TABLE IF NOT EXISTS `TousEnVacancesBD`.`COMPTE` (
  `ID_COMPTE` INT NOT NULL AUTO_INCREMENT,
  `ID_EMPLOYE` INT NOT NULL,
  `LOGIN` VARCHAR(45) NOT NULL,
  `MOT_DE_PASSE` VARCHAR(45) NOT NULL,
  `ROLE` VARCHAR(45) NULL DEFAULT 'EMPLOYE',
  PRIMARY KEY (`ID_COMPTE`),
  CONSTRAINT `fk_COMPTES_EMPLOYE`
    FOREIGN KEY (`ID_EMPLOYE`)
    REFERENCES `TousEnVacancesBD`.`EMPLOYE` (`ID_EMPLOYE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_COMPTE_EMPLOYE` ON `TousEnVacancesBD`.`COMPTE` (`ID_EMPLOYE` ASC) ;

CREATE UNIQUE INDEX `ID_COMPTE_UNIQUE` ON `TousEnVacancesBD`.`COMPTE` (`ID_COMPTE` ASC) ;

CREATE INDEX `fk_COMPTES_EMPLOYE` ON `TousEnVacancesBD`.`COMPTE` (`ID_EMPLOYE` ASC) ;


-- -----------------------------------------------------
-- Table `TousEnVacancesBD`.`CONGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TousEnVacancesBD`.`CONGE` ;

CREATE TABLE IF NOT EXISTS `TousEnVacancesBD`.`CONGE` (
  `ID_CONGE` INT NOT NULL AUTO_INCREMENT,
  `ID_EMPLOYE` INT NOT NULL,
  `DATE_DEBUT` DATE NOT NULL,
  `DATE_FIN` DATE NOT NULL,
  `DUREE_JOURS` INT NOT NULL,
  `DATE_DEMANDE` DATE NOT NULL,
  `STATUT_DE_LA_DEMANDE` VARCHAR(16) NOT NULL DEFAULT 'en cours',
  `DATE_TRAITEMENT` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CONGE`),
  CONSTRAINT `fk_CONGE_EMPLOYE`
    FOREIGN KEY (`ID_EMPLOYE`)
    REFERENCES `TousEnVacancesBD`.`EMPLOYE` (`ID_EMPLOYE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CONGE_EMPLOYE_idx` ON `TousEnVacancesBD`.`CONGE` (`ID_EMPLOYE` ASC) ;

CREATE UNIQUE INDEX `ID_CONGE_UNIQUE` ON `TousEnVacancesBD`.`CONGE` (`ID_CONGE` ASC) ;

CREATE INDEX `fk_CONGE_EMPLOYE` ON `TousEnVacancesBD`.`CONGE` (`ID_EMPLOYE` ASC) ;


-- -----------------------------------------------------
-- Table `TousEnVacancesBD`.`PROJET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TousEnVacancesBD`.`PROJET` ;

CREATE TABLE IF NOT EXISTS `TousEnVacancesBD`.`PROJET` (
  `ID_PROJET` INT NOT NULL AUTO_INCREMENT,
  `SUJET` VARCHAR(45) NOT NULL,
  `CLIENT` VARCHAR(45) NOT NULL,
  `STATUT` VARCHAR(45) NOT NULL DEFAULT 'en cours',
  PRIMARY KEY (`ID_PROJET`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_PROJET_UNIQUE` ON `TousEnVacancesBD`.`PROJET` (`ID_PROJET` ASC) ;


-- -----------------------------------------------------
-- Table `TousEnVacancesBD`.`EMPLOYE_has_PROJET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TousEnVacancesBD`.`EMPLOYE_has_PROJET` ;

CREATE TABLE IF NOT EXISTS `TousEnVacancesBD`.`EMPLOYE_has_PROJET` (
  `ID_EMPLOYE` INT NOT NULL,
  `ID_PROJET` INT NOT NULL,
  CONSTRAINT `fk_EMPLOYE_has_PROJET_EMPLOYE`
    FOREIGN KEY (`ID_EMPLOYE`)
    REFERENCES `TousEnVacancesBD`.`EMPLOYE` (`ID_EMPLOYE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYE_has_PROJET_PROJET`
    FOREIGN KEY (`ID_PROJET`)
    REFERENCES `TousEnVacancesBD`.`PROJET` (`ID_PROJET`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EMPLOYE_has_PROJET_EMPLOYE` ON `TousEnVacancesBD`.`EMPLOYE_has_PROJET` (`ID_EMPLOYE` ASC) ;

CREATE INDEX `fk_EMPLOYE_has_PROJET_PROJET` ON `TousEnVacancesBD`.`EMPLOYE_has_PROJET` (`ID_PROJET` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ----------------------REMPLISSAGE DE LA TABLE EMPLOYE-------------------------------------------------------------------
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('jean.bonbeurre@mail.com','Bonbeurre','Jean');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('harry.covert@mail.fr','Covert','Harry');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('gerard.menvusa@mail.com','Menvusa','Gerard');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM,GRADE)VALUES('remy-manu@mail.com','Manu','Remy','boss');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('alain.terrieur@mail.fr','Terrieur','Alain');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('jermy.delessencedanslavoiture@prout.lol','Delessencedanslavoiture','Jeremy');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('henry.tournelle@wololo.com','Tournelle','Henry');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('denis.chon@hohohoho.lol','Chon','Denis');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('larry.bambelle@mdr.fr','Bambelle','Larry');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('adrienne.kepoura@email.com','Kepoura','Adrienne');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('alain.proviste@hotmail.fr','Proviste','Alain');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('alex.terrieur@gmail.com','Terrieur','Alex');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('ali.gator@yopmail.com','Gator','Ali');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('eva.zion@adresse.mail','Zion','Eva');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('guy.yiottine@machin.de','Yiottine','Guy');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('jacques.ouzi@erreur.grave','Ouzi','Jacques');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('julien.ternette@internet.com','Ternette','Julien');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('lara.tatouille@email.fr','Tatouille','Lara');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('anne.atomie@email.com','Atomie','Anne');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('maude.erateur@mail.fr','Erateur','Maude');
INSERT INTO tousenvacancesbd.employe (ADRESSE_MAIL,NOM,PRENOM)VALUES('nordine.ateur@mail.fr','Ateur','Nordine');


-- ---------------------------REMPLISSAGE DE LA TABLE COMPTE-------------------------------------------
DELIMITER #
CREATE PROCEDURE remplir_comptes()
begin

declare id_counter int unsigned default 1;
declare max_id int unsigned default 22;
start transaction;
while id_counter < max_id DO
	INSERT INTO tousenvacancesbd.compte
	(LOGIN, MOT_DE_PASSE, ROLE, ID_EMPLOYE)
	VALUES (
	(SELECT NOM FROM EMPLOYE WHERE ID_EMPLOYE = id_counter),
	(SELECT PRENOM FROM EMPLOYE WHERE ID_EMPLOYE = id_counter),
	(SELECT GRADE FROM EMPLOYE WHERE ID_EMPLOYE = id_counter),
	id_counter);
    set id_counter=id_counter+1;
end while;
commit;
end#
end

DELIMITER ;
call remplir_comptes();

-- -------------------------CREATION DE 4 DEMANDES -------------------------------------------------
INSERT INTO `tousenvacancesbd`.`conge` (`DATE_DEBUT`, `DATE_FIN`, `DUREE_JOURS`, `DATE_DEMANDE`, `ID_EMPLOYE`, `STATUT_DE_LA_DEMANDE`, `DATE_TRAITEMENT`) VALUES ('2019-04-08', '2019-04-18', '9', '2019-01-01', '15', 'refusee', '2019-01-20');
INSERT INTO `tousenvacancesbd`.`conge` (`DATE_DEBUT`, `DATE_FIN`, `DUREE_JOURS`, `DATE_DEMANDE`, `ID_EMPLOYE`, `STATUT_DE_LA_DEMANDE`, `DATE_TRAITEMENT`) VALUES ('2019-04-22', '2019-04-26', '5', '2019-01-21', '15', 'acceptee', '2019-01-25');
INSERT INTO `tousenvacancesbd`.`conge` (`DATE_DEBUT`, `DATE_FIN`, `DUREE_JOURS`, `DATE_DEMANDE`, `ID_EMPLOYE`, `STATUT_DE_LA_DEMANDE`, `DATE_TRAITEMENT`) VALUES ('2019-04-29', '2019-05-24', '20', '2019-03-15', '9', 'refusee', '2019-03-17');
INSERT INTO `tousenvacancesbd`.`conge` (`DATE_DEBUT`, `DATE_FIN`, `DUREE_JOURS`, `DATE_DEMANDE`, `ID_EMPLOYE`) VALUES ('2019-06-20', '2019-06-27', '5', '2019-04-11', '2');

-- -------------------------CREATION DE 3 PROJETS, et associtation de quelques employes --------------
INSERT INTO tousenvacancesbd.projet (SUJET, CLIENT) VALUES ('conquérir le monde', 'Dr Méchant');
INSERT INTO tousenvacancesbd.projet (SUJET, CLIENT) VALUES ('construire un barrage', 'Jean-Claude Von Dam');
INSERT INTO tousenvacancesbd.projet (SUJET, CLIENT) VALUES ('gagner des sous', 'Oncle Picsou');

Insert INTO employe_has_projet (id_employe, id_projet) VALUES (1, 1);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (2, 2);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (3, 3);

Insert INTO employe_has_projet (id_employe, id_projet) VALUES (5, 1);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (6, 2);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (7, 3);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (8, 1);


Insert INTO employe_has_projet (id_employe, id_projet) VALUES (9, 1);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (10, 1);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (11, 1);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (12, 1);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (13, 1);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (14, 1);


Insert INTO employe_has_projet (id_employe, id_projet) VALUES (17, 2);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (18, 2);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (19, 2);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (20, 2);
Insert INTO employe_has_projet (id_employe, id_projet) VALUES (21, 2);

SELECT * FROM tousenvacancesbd.employe;
SELECT * FROM tousenvacancesbd.compte;
SELECT * FROM tousenvacancesbd.projet;
SELECT * FROM tousenvacancesbd.employe_has_projet;
SELECT * FROM tousenvacancesbd.conge;
